# -*- coding: utf-8 -*-
from __future__ import unicode_literals

OPEN = 'OPEN'
IN_PROGRESS = 'PROGRESS'
IN_REVIEW = 'REVIEW'
DONE = 'DONE'
BLOCKED = 'BLOCKED'
TASK_STATUS = (
    (OPEN[0], OPEN),
    (IN_PROGRESS[0], IN_PROGRESS),
    (IN_REVIEW[0], IN_REVIEW),
    (DONE[0], DONE),
    (BLOCKED[0], BLOCKED),
)

DETAIL = 'DETAIL'
DELETE = 'DELETE'
CREATE = 'CREATE'
UPDATE = 'UPDATE'
ACTION = (
    (DETAIL, DETAIL),
    (DELETE, DELETE),
    (CREATE, CREATE),
    (UPDATE, UPDATE),
)
